{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vulntracker.fullname" . }}
  labels:
    {{- include "vulntracker.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "vulntracker.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretKey }}
        property: SECRET_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretKey }}
        property: DATABASE_URL
    - secretKey: ADMIN_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretKey }}
        property: ADMIN_API_KEY
{{- end }}
